default:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: "{{ env_var('MSSQL_HOST') }}"
      port: 1433
      database: "{{ env_var('MSSQL_DATABASE') }}"
      schema: model
      user: "{{ env_var('MSSQL_USER') }}"
      password: "{{ env_var('MSSQL_PASSWORD') }}"
      trust_cert: true
